### ISSUE TITLE
Some general feedback and suggestions

### ISSUE THREAD

**Issue by linaori** [ruvents/form-wizard-bundle#1]
First of all, I like how this bundle is set up! The way you create a wizard is similar to what I had in mind, but never really had the need to build. I have some general feedback that I hope will increase the quality of this package.

#### Autowiring
In the [Extension](https://github.com/ruvents/form-wizard-bundle/blob/master/DependencyInjection/RuventsFormWizardExtension.php#L22) you autowire the classes, please don't do this as it's very fragile in applications. Bundles should be very explicit in which services and dependencies they define.

Instead, I would suggest to look at the [PHP DSL](https://symfony.com/blog/new-in-symfony-3-4-php-based-configuration-for-services-and-routes), which avoids the XML and YML dependencies.

#### Form Handling
Currently this package requires a specific way of retrieving the wizard, which is then used similar to how forms are used:
```php
$form = $step->createForm()->handleRequest($request);
```

Currently we're trying to abstract away the form handling in our company in a nice way, which is incompatible with the current design of the wizard. I can imagine that the handling of this wizard could also be abstracted away in the exact same way:
 - You get a handler
 - You handle the form
 - You get something back
 - Controller handles the return

```php
class YourController extends Controller
{
    public function formAction(Request $request, MyEntityUser $user)
    {
        $handler = $this->get('hostnet.form_handler.factory')->create(MyFormHandler::class);

        if (($response = $handler->handle($request, new MyFormData())) instanceof RedirectResponse) {
            return $response;
        }

        // regular or in-valid flow
        return $this->render->renderView('/your/form.html.twig', [
            'form' => $handler->getForm()->createView()
        ]);
    }
}
```

To make this bundle more compatible, it would be really neat to see some form of integration one way or another with the [hostnet/form-handler-bundle](https://github.com/hostnet/form-handler-bundle). As your bundle is still in an early stage, would you be willing to consider some form of optional integration (one way or the other)?

**Comment by vudaltsov** [comment]
@iltar , thank you very much for your feedback.

I definitely agree with the autowiring proposal and will fix it in every bundle of mine. It makes sense to be specific about injections in 3rd-party libs.

The question about handling is also very useful. The inability to abstract handling from the wizard points at an architectural problem.

Hope to fix both pretty soon!
